let imgName = [
    "00",
    "Ratak Monodosico - film",
    "Designinspiriation - creative photography",
    "Korb - skill",
    "1995生まれ - Image in Japan",
    "Arcin Sagdic - an otherworldy eye",
    "Jin dallar & Park Woohyuk - Archive annyeong",
    "Ree Liu - The Fashion Graduate Diploma",
    "Jenamyung - Graphics",
    "Laurence Demaison - Photography",
    "Mund Reihen - Cruello",
    "Henie Onstad Art Centre - Fluxus",
    "Angfriend - Mouthful of Lies",
    "Xavier Bangbang - The Ear",
    "M - about eye",
    "Alphonse Bertillon - Synoptic Table of Physiognomic Traits",
    "John Hilliard - Galerie Max Hetzler",
    "Tomoko Sawada - ID 400 Project",
    "Promptuarium - Human Cattle",
    "Kamarulzaman Bin Mohamed Sapiee - Facial Codes",
    "Raji Purcell - Meet the Class",
    "Assuntos Criativos - QR Codes criativos que funcionam",
    "Bruno Munari & Giovanni Belgrano - Cards form Images of Reality",
    "Gallery of Bernhard Leitner - Sound Spaces",
    "Charlotte Owst - Typology",
    "Jin dallar & Park Woohyuk - Archive annyeong",
    "Jin dallar & Park Woohyuk - Archive annyeong",
    "Daniela Damaschin - Funky Type",
    "5:11AM - networkism",
    "Mrkism - Unfold Human Consciousness",
    "Hvixian Designs - Zoanthids Identification Poster",
    "Gabriela Catalina - microbiology",
    "Popper Font - microbiology",
    "Daily Petri Fish - microbiology",
    "AROS - cool, calm and collected",
    "Exprimidores - microbiology",
    "Melvin L Prueitt - Picture System",
    "Reem - microbiology",
    "Merlin Sheldrake & Rupert Sheldrake - Determinants of Faraday Wave-Patterns in Water Samples Oscillated Vertically at a Range of Frequencies from 50-200 Hz",
    "David Hutton - 12 Water Textures",
    "Hai Lanzhu - Ancient Chinese Jade Topiary Summary",
    "Hai Lanzhu - Ancient Chinese Jade Topiary Summary",
    "Hai Lanzhu - Ancient Chinese Jade Topiary Summary",
    "Rob Scharein - Knots are Algebraically Dull 2",
    "Karl Nawrot - A Graphic Designer Who Thinks like an Architect",
    "Dina Silanteva - Typographic Music",
    "Pop Science - Who knows What Glows",
    "S.P - Editorial Designe",
    "S.P - Editorial Designe",
    "Christian Boltanski - Inventarios de objetos personales",
    "Modernism is crap - Grid",
    "John Batho - Galerie",
    "Ekkawit - ROck isolated on white background",
    "Solaine - the levin sky days",
    "Soo Minimally - Pathed",
    "Bieler Brief - Geoarchitecture",
    "Melvin L prueitt - Writing for the Evolution",
    "abdz - VHS Packaging",
    "Sharon Gong - Back Catalogue",
    "Sharon Gong - Back Catalogue",
    "Arthur Buxton - 67 Years of Classix Sci-Fi Covers",
    "Saatchiart - portraits of 35mm",
    "Flashbak - Blank VHS Cassette Packaging Design Trends",
    "Munich - Deisgn Studio",
    "Weebly - Typologies",
    "Patricia Grabowicz - Chews a Character",
    "Juyeon Kim - Scaletone",
    "Fujiya Milky - Candy box and wrapper 1970s",
    "Lesha Galkin - Gift Set for P.Y.E",
    "Mason - Wild CHerry Dots Candy box",
    "McDonald - McDonaldland Cookie box",
    "McDonald - McDonaldland Cookies 1974",
    "Jason Liebig - Marukawa Straberry & Orange Bubble Gum boxes",
    "Jason Liebig - Lemonhead two-sided candy box",
    "Hohoemi - Graphic Design",
    "Gior Konducta - Graphic Design",
    "M&M - M&Ms Plain Chocoloate Candies",
    "Underson - Graphic Deisgn",
    "McDonald - McDonald x BTS ",
    "Unodos - Packaging Design",
    "Карина - Newsprint",
    "Carnets de tracerse - Collection de petits sachets en papie",
    "Easy Crafts Ideas - DIY Doll Crafts",
    "Doll Printies - Drinks Page 3",
    "Hozna on Deviant Art - Dried Fruit Package Design",
    "Ольга Шилина - Packaging Design",
    "Creative Blog - Packaging Design",
    "Amy Peppler Adams - Penny Candy Handmade",
    "Creatief In Minis - Packaging Design",
    "Robert Marks - The Dymaxion World of Buckminster Fuller",
    "Shigeo Fukuda - Japanese Poster: In the U.S.A ",
    "Paiheme - Paiheme Studio",
    "Daniela Rivera - Caja Cereales",
    "Hohoemi - Packaging Design",
    "Jarhoon Choi - Search System",
    "Supremat Spacelines - NFT collection",
    "Bureau Borsche - Technofolk",
    "Gumroad - Digital assets for creator",
    "Monish Khara - Stickers",
    "Taiwan Design Center - 台灣品質～日常に台湾クオリティーを。～",
    "Also - Production Process",
    "Hanna Chen - Packaging Design",
    "Unknow - Does it Pop",
    "Unknow - inner consistensy",
    "D Duzaru - we stand as one ",
    "Chen Shijie - Herbal Medicine",
    "Hankyung - Poster",
    "Gainax - EVA",
    "Taller Abasolo - O.M.A. Diagram Tokio",
    "Shannon Quinn - Asian Food A4 Illustrated",
    "YIS.ubeco - P.E.A.C",
    "Dejima Graph - Trash collect",
    "Kitac - Poster",
    "Dejima Graph - Sakinaga",
    "Shingo - Flyer Archive JP",
    "Razku Shutinstva - Japanese stamp from 1937",
    "Spyropoulos Studio - Architect",
    "Other Peter - Stay Home ",
    "Tang Kwok-hin - Artemis Dreaming",
    "Tang Kwok-hin - Artemis Dreaming",
    "Tang Kwok-hin - Artemis Dreaming",
    "Tang Kwok-hin - Artemis Dreaming",
    "Line Kamala - Selected Artwork",
    "Gilad Benari - Walk of Life",
    "Gilad Benari - Walk of Life",
    "JF Ptak Science Books - Found-Modern Art in Stone ",
    "Gelbes Herz - Mumok",
    "Internet Archive - Diffraction patterns for natural and synthetic fibers",
    "S.P - Poster",
    "Unknow - Poster",
    "Unknow - Poster",
    "Bruno Munari - Creative Wall Decor",
    "Matej Vojtus - Graphic Work",
    "Nike - Poster",
    "Bnaoia Moraia - Taka Art Univeristy Work 2018",
    "Marco Biraghi - Appunti su Global Tools",
    "Microcities - Meauring Space ",
    "Will Redman - Book ",
    "Univeristy of Washington - Spiral Synthesis",
    "Gallery of Bernhard Leitner - Sound Spaces",
    "Jonatan Kuna - Graphic poster for NiteVibes",
    "Anna Uddenberg - News",
    "Frontispiece Friday - Focused Light",
    "Ben F.Laposky - Electronic Abstractions: Mathematics in Design ",
    "Spliff - Tuesday 8/27/2013",
    "Koloman Moser - The Curve in the Line",
    "Fromatt - Shading Medium Catalog",
    "Bugdoll - Old Sketches",
    "Moniker - Promotional Poster",
    "Dan Slavinsky - Drawings from the ENd of Time Bartlett",
    "Clément Masurier - Chapitre Un ",
    "Sarah Wigglesworth - dining tables",
    "Yayoi Kusama - Louis Vuitton Pop Up Poster",
    "Lateral Office - Gallery of Arctic Food network ",
    "VICE Magazine - Whole Earth Catalog",
    "Unknow - The book Design",
    "Spvz - poster",
    "Rafaël Rozendaal - The Shift",
    "Chris Ashworth - Ray Gun 56 Subscription Page Ad",
    "Spring of Mathematics - Kurven I/II",
    "The Ankh Life Projectm - Tab Geometry",
    "Taylor Hodge - Strange Map as Teroid",
    "Deejay - Repress Tracks: A1: Machine 1",
    "Nyua - a1xy",
    "Nyua - a1xy",
    "JP Haynie - Actual Source: Call Now Symbol ",
    "Aloe City Records - Anathema",
    "Lewis P Brown - Daydreamn",
    "Vinyl - Inversia 1",
    "Grafook - Graphcs this is grey like",
    "Vinyl - Aqueduct",
    "Jensen Interceptor - Hydro Systems",
    "Martin Wilson - Look Both Way",
    "Unknow - Standard Energy Chain",
    "Dead Ego Society - Infinity",
    "INIT - Gravity",
    "Yeonjun - Poster",
    "Kaleidoscope - General Index",
    "Ilya Perevedentsev - Poster",
    "Ross Paul McEwan - generative Art",
    "S.P - generative Art",
    "Mvibrrrr - generative Art",
    "Various - Tlub Cools",
    "angelpr1nce - generative Art",
    "Steven Skov Holt & Mara Holt Skov - The Conspicuous Transformation of Everyday ",
    "Safehavenhq - generative Art",
    "S.P - generative Art",
    "S.P - generative Art",
    "Jyni Ong - Bluer Flight",
    "Dorha - generative Art",
    "D.E - Design Everywhere",
    "Tomasorban - generative Art",
    "research urbanfuture - Material and Porosity.",
    "Unknow - generative Art",
    "Daily Art - Geometric Shapes",
    "Jason Combs - mindframe",
    "Huanhuan Wang - 60/365",
    "Society6 - Designed Wall Art",
    "Nicolas Jaar - Telas",
    "Nicolas Jaar - Telas",
    "Garry Ing - 3",
    "Garry Ing - 5",
    "Jan en Randoald - Poster",
    "David Rudnick - hi res",
    "Yi Yang - Typhoon",
    "Onformative - Skype visualization poster",
    "Acne Studio - generative art",
    "Rikkawa W - Poster",
    "Antonio Carrau - collages",
    "Han Gao - Perfect Print ",
    "Jubru - Photos on Flickr. Juburu",
    "Architecture and Design Magazine - the Annual Skyscraper Architectural Competition",
    "Bacteria - print",
    "imgclub - Graphics this is grey likes",
    "Macoto Murayama - Intricate Blueprints of Flowers",
    "Fuji - AGFA",
    "Monsoon Assemblages Chennai - MONCEAUX-2",
    "9gag - firworks",
    "Macoto Murayama - generated Illustrations of Flowers",
    "Judith Schaechter - House of Rats",
    "Print for Crack Magazine 101 - Two Dancers",
    "Everyday Practice - REAL-Real City",
    "Ampproject - Poster",
    "British Petrography - 1888",
    "Gabriel Boye - Photography",
    "wzrdryAV - Midnight Visions",
    "River Park - 705 Anarchitecture research",
    "Urban Environment - Vernacular Typograohy",
    "Kier Kool Spit - Poster",
    "Axel Key & Gustaf Retzius - Studies in Anatomy of the Nervous System and Connective Tissue",
    "Иллюстрации для - Le Monde Magazine",
    "Hannah - Lagoonist Photo",
    "Suri Cheng - Poster",
    "Jialin Huang - My Teeth",
    "Indieground Deisgn - Weekly Inspiration Does ",
    "Farwhoo - Rabbits No Hats",
    "Unknow - Factory door Sticker",
    "György Ligeti - garadinervi repertori",
    "Dick Klavans - Art / Science",
    "Günther Domenig & Eilfried Huth - Frac centre",
    "Max Neuhaus - Aural topography Times Square",
    "SICA - Data mining and visualization ",
    "Flora Chan - Brave New World",
    "Gunther Kleinert - the artist who sees the music",
    "Unknow - Helium sppech and a brief introduction to speech acoustics",
    "Publications - temporal variation in natural remanent magnetization observed for Pacific plate basement rocks",
    "Shusanzc Shusan - Voice graph",
    "Language Sindanger - The sounds of Language",
    "Daniel Graf - Poster",
    "Behnaz Assadi - Picasso paintings ",
    "Archdaily - Gallery of Learning by Doing",
    "Science Source - Speech Patterns",
    "Sukgo - Cymascope",
    "Neeraj Bhatia - Dredgescaping Toledo",
    "Unknow - The Eutopian Encyclopedia",
    "BloomingData - Pixel plot of traffic data",
    "Mvibrrrr - Photography",
]


console.log(imgName[1]);


// I want to print the name
